version: '3'
services:
  web1:
    build: .
    ports:
      - "80"
  web2:
    build: .
    ports:
      - "80"
  web3:
    build: .
    ports:
      - "80"
  nginx:
    image: nginx:latest
    ports:
      - "9090:9090"
    depends_on:
      - web1
      - web2
      - web3
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
  redis:
    image: redis:latest
    ports:
      - "6379:6379"